### ISSUE TITLE
Why is it obfuscated?

### ISSUE THREAD

**Issue by Notexe** [AliceorjustAlicia/AllyMods#1]
I don't think I can trust running this program without being able to see it's source code. How do I know that it won't be a virus that does something to my PC?

I'm hoping you will release the source code in the future for this project, in the meantime I will not be risking running this.

**Comment by AliceorjustAlicia** [comment]
> I don't think I can trust running this program without being able to see it's source code. How do I know that it won't be a virus that does something to my PC?
> 
> I'm hoping you will release the source code in the future for this project, in the meantime I will not be risking running this.

Greetings, Notexe!

I am sorry for the late response, been unavailable and working on different projects that are thoroughly not related to AllyMods.

The reason for the obfuscation of this software is certainly so people could /not/ manipulate by any means the code that I have created. I am not doing this with a malicious intention, but to prevent many disgraces that sadly do happen, like people claiming the program to be theirs or even poorer, attempting to sell it.

I plan to release the source code at a given point, but for now I am not plotting to do so. You are totally right nevertheless, and I am not forcing you to use this program if you do not want.

It is paramount to highlight that it incorporates no virus or any other malicious code. I will make sure to include a virus detection link of the file if it somehow helps you.

If you have further inquiries, you are invited to add me on Steam (https://steamcommunity.com/id/codingalice/) or open more issues through Github. I will try to reply much faster than this.

- Alice ♥
